version: '3.1'
services:
  frpc:
    container_name: frpc
    build:
      context: ../
    volumes:
      - ./logs:/frp/logs
      - ./frpc.ini:/frp/frpc.ini:ro
    restart: always
    entrypoint: /frp/frpc -c /frp/frpc.ini
    network_mode: "host"
